server:
  port: 7001

eureka:
  instance:
    # eureka 服务端的实例名称
    hostname: eureka7001.com
  client:
    # false 表示不向注册中心注册自己
    register-with-eureka: false
    # false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与 Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://eureka7002.com:7002/eureka/
      # 恢复单机版 Eureka
      defaultZone: http://localhost:7001/eureka/
# 关闭自我保护机制，保证不可用的服务即使剔除 false  默认为 true
  server:
    enable-self-preservation: false
    #剔除服务时间
    eviction-interval-timer-in-ms: 2000