server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
      routes:
        # 路由的 ID，没有固定规则但要求唯一，建议配合服务名
        - id: payment_routh
          # 匹配后提供服务的路由地址
          # uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            # 断言，路径相匹配的进行路由
            - Path=/get/**

        # 路由的 ID，没有固定规则但要求唯一，建议配合服务名
        - id: payment_routh2
          # 匹配后提供服务的路由地址
          # uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          #          filters:
          #            - AddRequestParameter=X-Request-Id,1024  # 过滤器工厂会在匹配的请求头加上一对请求头，名称为 X-Request-Id，值为 1024
          predicates:
            # 断言，路径相匹配的进行路由
            - Path=/pay/lb
#            - Query=username, \d+  # 要有参数名称并且是正整数才能路由
#            - Method=GET
#            - Host=**.sgj.com
#            - Header=X-Request-Id, \d+   # 请求头中要有X-Request-Id属性并且值为整数的正则表达式
#            - Cookie=username,zzyy
#            - After=2021-11-20T10:59:34.102+08:00[Asia/Shanghai]
#            - Before=2021-05-20T10:59:34.102+08:00[Asia/Shanghai]
#            - Between=2021-05-20T10:59:34.102+08:00[Asia/Shanghai],2021-05-22T10:59:34.102+08:00[Asia/Shanghai]

eureka:
  instance:
    hostname: cloud-gateway-service
  # 服务提供者 provider 注册进 eureka 服务列表中
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka