version: '3'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ew2q#dDqes22e # 设置root帐号密码
    ports:
      - 3306:3306
    volumes:
      - /mydata/mysql/data/db:/var/lib/mysql # 数据文件挂载
      - /mydata/mysql/data/conf:/etc/mysql/conf.d # 配置文件挂载
      - /mydata/mysql/log:/var/log/mysql # 日志文件挂载
  redis:
    image: redis:7
    container_name: redis
    command:  redis-server --requirepass ew2q#dDqes22e --appendonly yes
    restart: always
    volumes:
      - /mydata/redis/data:/data # 数据文件挂载
    ports:
      - 7298:6379
  nginx:
    image: nginx:1.22
    container_name: nginx
    restart: always
    volumes:
      - /mydata/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:rw # 配置文件挂载
      - /mydata/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:rw # 默认配置文件挂载
      - /mydata/nginx/ssl:/ssl:rw # 证书
      - /mydata/nginx/html:/usr/share/nginx/html:rw # 静态资源根目录挂载
      - /mydata/nginx/log:/var/log/nginx:rw # 日志文件挂载
    ports:
      - 80:80
      - 443:443
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    restart: always
    volumes:
      - /mydata/rabbitmq/data:/var/lib/rabbitmq # 数据文件挂载
      - /mydata/rabbitmq/log:/var/log/rabbitmq # 日志文件挂载
    ports:
      - 5672:5672
      - 1883:1883
      - 15672:15672
  elasticsearch:
    image: elasticsearch:7.13.3  #镜像
    container_name: elasticsearch  # 定义容器名称
    restart: always
    environment:
      - "cluster.name=elasticsearch" # 设置集群名称为elasticsearch
      - "discovery.type=single-node" # 以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m" # 设置使用jvm内存大小
    volumes:
      - /mydata/elasticsearch/plugins:/usr/share/elasticsearch/plugins # 插件文件挂载
      - /mydata/elasticsearch/data:/usr/share/elasticsearch/data # 数据文件挂载
    ports:
      - 9200:9200
  kibana:
    image: kibana:7.13.3
    container_name: kibana
    restart: always
    depends_on:
      - elasticsearch # kibana在elasticsearch启动之后再启动
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200 # 设置访问elasticsearch的地址
    ports:
      - 5601:5601
  logstash:
    image: logstash:7.13.3
    container_name: logstash
    restart: always
    volumes:
      - /mydata/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf # 挂载logstash的配置文件
    depends_on:
      - elasticsearch # kibana在elasticsearch启动之后再启动
    links:
      - elasticsearch:es # 可以用es这个域名访问elasticsearch服务
    ports:
      - 4560:4560
      - 4561:4561
      - 4562:4562
      - 4563:4563
  mongo:
    image: mongo:4
    container_name: mongodb
    command: --auth
    restart: always
    volumes:
      - /mydata/mongodb/db:/data/db # 数据文件挂载
    ports:
      - 27797:27017
  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9090:9090
    restart: always
    command: server /data --console-address ":9090" --address ":9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: ew2q#dDqes22e
      MINIO_SERVER_URL: http://www.sgj.asia:9000 # 设置分享文件地址，否则分享地址ip会为docker内部ip
    volumes:
      - /mydata/minio/data:/data
      - /mydata/minio/config:/root/.minio
#  nacos:
#    image: nacos/nacos-server
#    container_name: nacos
#    ports:
#      - 8848:8848
#    restart: always
#    environment:
#      JVM_XMS: 512m
#      JVM_XMX: 512m
#      PREFER_HOST_MODE: hostname
#      MODE: standalone
#      SPRING_DATASOURCE_PLATFORM: mysql
#      MYSQL_SERVICE_HOST: sgj.asia
#      MYSQL_SERVICE_PORT: 3306
#      MYSQL_SERVICE_USER: root
#      MYSQL_SERVICE_PASSWORD: ew2q#dDqes22e
#      MYSQL_SERVICE_DB_NAME: nacos_config