insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'root', 'PGS+', '0', 'root', 'root', '1', 'ESOP', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_basicdata_view', '基础信息', '0', 'root', 'esop:basicdata:view', '1', '基础信息', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_prodLine_view', '产线信息', '0', 'esop_basicdata_view', 'esop:prodLine:view', '1', '产线信息', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_procedureDictionary_view', '工序字典', '0', 'esop_basicdata_view', 'esop:procedureDictionary:view', '1', '工序字典', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_station_view', '工位信息', '0', 'esop_basicdata_view', 'esop:station:view', '1', '工位信息', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_product_view', '产品信息', '0', 'esop_basicdata_view', 'esop:product:view', '1', '产品信息', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_dept_view', '部门信息', '0', 'esop_basicdata_view', 'esop:dept:view', '1', '部门信息', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_processRoute_view', '工艺路线', '0', 'esop_basicdata_view', 'esop:processRoute:view', '1', '工艺路线', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_doc_view', '文档管理', '0', 'root', 'esop:doc:view', '1', '文档管理', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_work_view', '作业管理', '0', 'root', 'esop:work:view', '1', '作业管理', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_workTemplate_view', '作业模板', '0', 'esop_work_view', 'esop:workTemplate:view', '1', '作业模板', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_workInfo_view', '作业计划', '0', 'esop_work_view', 'esop:workInfo:view', '1', '作业计划', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_stationMonitior_view', '工位监控', '0', 'root', 'esop:stationMonitior:view', '1', '工位监控', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_noticeMana_view', '工位通知', '0', 'root', 'esop:noticeMana:view', '1', '工位通知', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_notice_view', '通知管理', '0', 'esop_noticeMana_view', 'esop:notice:view', '1', '通知管理', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_noticeDetail_view', '通知记录', '0', 'esop_noticeMana_view', 'esop:noticeDetail:view', '1', '通知记录', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_andon_view', '安灯呼叫', '0', 'root', 'esop:andon:view', '1', '安灯呼叫', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_andonItem_view', '安灯项', '0', 'esop_andon_view', 'esop:andonItem:view', '1', '安灯项', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_andonBoard_view', '安灯看板', '0', 'esop_andon_view', 'esop:andonBoard:view', '1', '安灯看板', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_andonRecord_view', '安灯记录', '0', 'esop_andon_view', 'esop:andonRecord:view', '1', '安灯记录', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productTask_view', '产线任务', '0', 'root', 'esop:productTask:view', '1', '产线任务', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_procReqmst_view', '生产订单', '0', 'esop_productTask_view', 'esop:procReqmst:view', '1', '生产订单', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_simplePlan_view', '产线计划', '0', 'esop_productTask_view', 'esop:simplePlan:view', '1', '产线计划', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productPlan_view', '产线计划', '0', 'esop_productTask_view', 'esop:productPlan:view', '1', '产线计划', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productReport_view', '报工记录', '0', 'esop_productTask_view', 'esop:productReport:view', '1', '报工记录', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_customLib_view', '不良图库', '0', 'esop_productTask_view', 'esop:customLib:view', '0', '不良图库', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_reportAnalysis_view', '报表分析', '0', 'root', 'esop:reportAnalysis:view', '1', '报表分析', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productPlanProgress_view', '产线计划进度表', '0', 'esop_reportAnalysis_view', 'esop:productPlanProgress:view', '1', '产线计划进度表', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productPlanDetails_view', '产线计划明细表', '0', 'esop_reportAnalysis_view', 'esop:productPlanDetails:view', '1', '产线计划明细表', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productPlanSummary_view', '产线计划汇总表', '0', 'esop_reportAnalysis_view', 'esop:productPlanSummary:view', '1', '产线计划汇总表', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_reportRecordDetails_view', '报工记录明细表', '0', 'esop_reportAnalysis_view', 'esop:reportRecordDetails:view', '1', '报工记录明细表', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_reportRecordSummary_view', '报工记录汇总表', '0', 'esop_reportAnalysis_view', 'esop:reportRecordSummary:view', '1', '报工记录汇总表', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_pieceWageDetails_view', '计件工资明细表', '0', 'esop_reportAnalysis_view', 'esop:pieceWageDetails:view', '1', '计件工资明细表', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_pieceWageSummary_view', '计件工资汇总表', '0', 'esop_reportAnalysis_view', 'esop:pieceWageSummary:view', '1', '计件工资汇总表', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_prodLinePassRate_view', '产线合格率报表', '0', 'esop_reportAnalysis_view', 'esop:prodLinePassRate:view', '1', '产线合格率报表', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_prodLineRejectionRate_view', '产线报废率报表', '0', 'esop_reportAnalysis_view', 'esop:prodLineRejectionRate:view', '1', '产线报废率报表', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_prodLineOnTimeRate_view', '产线及时率报表', '0', 'esop_reportAnalysis_view', 'esop:prodLineOnTimeRate:view', '1', '产线及时率报表', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_prodLineCompletionRate_view', '产线完成率报表', '0', 'esop_reportAnalysis_view', 'esop:prodLineCompletionRate:view', '1', '产线完成率报表', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_kanBan_view', '看板管理', '0', 'root', 'esop:kanBan:view', '1', '看板管理', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'system_setup_view', '系统设置', '0', 'root', 'system:setup:view', '1', '系统设置', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'system_role_view', '角色管理', '0', 'system_setup_view', 'system:role:view', '1', '角色管理', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'system_user_view', '用户管理', '0', 'system_setup_view', 'system:user:view', '1', '用户管理', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'system_fileConfig_view', '文件设置', '0', 'system_setup_view', 'system:fileConfig:view', '1', '文件设置', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_terminal_view', '终端权限', '0', 'root', 'esop:terminal:view', '1', '终端设置', '');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'root');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_basicdata_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_prodLine_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_procedureDictionary_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_station_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_product_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_dept_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_processRoute_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_doc_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_work_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_workTemplate_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_workInfo_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_stationMonitior_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_noticeMana_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_notice_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_noticeDetail_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_andon_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_andonItem_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_andonBoard_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_andonRecord_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productTask_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_procReqmst_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_simplePlan_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productPlan_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productReport_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_customLib_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_reportAnalysis_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productPlanProgress_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productPlanDetails_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productPlanSummary_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_reportRecordDetails_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_reportRecordSummary_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_pieceWageDetails_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_pieceWageSummary_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_prodLinePassRate_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_prodLineRejectionRate_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_prodLineOnTimeRate_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_prodLineCompletionRate_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_kanBan_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'system_setup_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'system_role_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'system_user_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'system_fileConfig_view');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_terminal_view');
insert into sys_RoleResource(roleCode, resourceCode) values('admin', 'system_setup_view');
insert into sys_RoleResource(roleCode, resourceCode) values('admin', 'system_role_view');
insert into sys_RoleResource(roleCode, resourceCode) values('admin', 'system_user_view');
insert into sys_RoleResource(roleCode, resourceCode) values('admin', 'system_fileConfig_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'root');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_basicdata_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_prodLine_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_procedureDictionary_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_station_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_product_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_dept_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_processRoute_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_doc_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_work_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_workTemplate_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_workInfo_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_stationMonitior_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_noticeMana_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_notice_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_noticeDetail_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_andon_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_andonItem_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_andonBoard_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_andonRecord_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productTask_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_procReqmst_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_simplePlan_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productPlan_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productReport_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_customLib_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_reportAnalysis_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productPlanProgress_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productPlanDetails_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productPlanSummary_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_reportRecordDetails_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_reportRecordSummary_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_pieceWageDetails_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_pieceWageSummary_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_prodLinePassRate_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_prodLineRejectionRate_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_prodLineOnTimeRate_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_prodLineCompletionRate_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_kanBan_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'system_setup_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'system_role_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'system_user_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'system_fileConfig_view');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_terminal_view');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_prodLine_add', '新增', '1', 'esop_prodLine_view', 'esop:prodLine:add', '1', '产线信息--新增', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_prodLine_delete', '删除', '1', 'esop_prodLine_view', 'esop:prodLine:delete', '1', '产线信息--删除', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_prodLine_update', '修改', '1', 'esop_prodLine_view', 'esop:prodLine:update', '1', '产线信息--修改', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_prodLine_refresh', '刷新', '1', 'esop_prodLine_view', 'esop:prodLine:refresh', '1', '产线信息--刷新', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_prodLine_filter', '过滤', '1', 'esop_prodLine_view', 'esop:prodLine:filter', '1', '产线信息--过滤', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_prodLine_import', '导入', '1', 'esop_prodLine_view', 'esop:prodLine:import', '1', '产线信息--导入', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_prodLine_export', '导出', '1', 'esop_prodLine_view', 'esop:prodLine:export', '0', '产线信息--导出', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_prodLine_employee', '操作工', '1', 'esop_prodLine_view', 'esop:prodLine:employee', '1', '产线信息--操作工', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_procedureDictionary_add', '新增', '1', 'esop_procedureDictionary_view', 'esop:procedureDictionary:add', '1', '工序字典--新增', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_procedureDictionary_delete', '删除', '1', 'esop_procedureDictionary_view', 'esop:procedureDictionary:delete', '1', '工序字典--删除', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_procedureDictionary_update', '修改', '1', 'esop_procedureDictionary_view', 'esop:procedureDictionary:update', '1', '工序字典--修改', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_procedureDictionary_refresh', '刷新', '1', 'esop_procedureDictionary_view', 'esop:procedureDictionary:refresh', '1', '工序字典--刷新', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_procedureDictionary_filter', '过滤', '1', 'esop_procedureDictionary_view', 'esop:procedureDictionary:filter', '1', '工序字典--过滤', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_procedureDictionary_import', '导入', '1', 'esop_procedureDictionary_view', 'esop:procedureDictionary:import', '1', '工序字典--导入', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_procedureDictionary_export', '导出', '1', 'esop_procedureDictionary_view', 'esop:procedureDictionary:export', '0', '工序字典--导出', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_station_add', '新增', '1', 'esop_station_view', 'esop:station:add', '1', '工位信息--新增', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_station_delete', '删除', '1', 'esop_station_view', 'esop:station:delete', '1', '工位信息--删除', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_station_update', '修改', '1', 'esop_station_view', 'esop:station:update', '1', '工位信息--修改', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_station_refresh', '刷新', '1', 'esop_station_view', 'esop:station:refresh', '1', '工位信息--刷新', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_station_filter', '过滤', '1', 'esop_station_view', 'esop:station:filter', '1', '工位信息--过滤', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_station_import', '导入', '1', 'esop_station_view', 'esop:station:import', '1', '工位信息--导入', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_station_export', '导出', '1', 'esop_station_view', 'esop:station:export', '0', '产线信息--导出', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_product_add', '新增', '1', 'esop_product_view', 'esop:product:add', '1', '产品信息--新增', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_product_delete', '删除', '1', 'esop_product_view', 'esop:product:delete', '1', '产品信息--删除', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_product_update', '修改', '1', 'esop_product_view', 'esop:product:update', '1', '产品信息--修改', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_product_refresh', '刷新', '1', 'esop_product_view', 'esop:product:refresh', '1', '产品信息--刷新', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_product_filter', '过滤', '1', 'esop_product_view', 'esop:product:filter', '1', '产品信息--过滤', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_product_import', '导入', '1', 'esop_product_view', 'esop:product:import', '1', '产品信息--导入', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_product_export', '导出', '1', 'esop_product_view', 'esop:product:export', '0', '产品信息--导出', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_product_preview', '预览', '1', 'esop_product_view', 'esop:product:preview', '1', '产品信息--预览', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_dept_add', '新增', '1', 'esop_dept_view', 'esop:dept:add', '1', '部门信息--新增', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_dept_delete', '删除', '1', 'esop_dept_view', 'esop:dept:delete', '1', '部门信息--删除', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_dept_update', '修改', '1', 'esop_dept_view', 'esop:dept:update', '1', '部门信息--修改', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_dept_refresh', '刷新', '1', 'esop_dept_view', 'esop:dept:refresh', '1', '部门信息--刷新', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_dept_filter', '过滤', '1', 'esop_dept_view', 'esop:dept:filter', '1', '部门信息--过滤', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_dept_import', '导入', '1', 'esop_dept_view', 'esop:dept:import', '1', '部门信息--导入', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_processRoute_add', '新增', '1', 'esop_processRoute_view', 'esop:processRoute:add', '1', '工艺路线--新增', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_processRoute_delete', '删除', '1', 'esop_processRoute_view', 'esop:processRoute:delete', '1', '工艺路线--删除', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_processRoute_update', '修改', '1', 'esop_processRoute_view', 'esop:processRoute:update', '1', '工艺路线--修改', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_processRoute_refresh', '刷新', '1', 'esop_processRoute_view', 'esop:processRoute:refresh', '1', '工艺路线--刷新', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_processRoute_filter', '过滤', '1', 'esop_processRoute_view', 'esop:processRoute:filter', '1', '工艺路线--过滤', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_doc_addDir', '目录-新增', '1', 'esop_doc_view', 'esop:doc:addDir', '1', '文档管理--目录--新增', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_doc_updateDir', '目录-修改', '1', 'esop_doc_view', 'esop:doc:updateDir', '1', '文档管理--目录--修改', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_doc_deleteDir', '目录-删除', '1', 'esop_doc_view', 'esop:doc:deleteDir', '1', '文档管理--目录--删除', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_doc_refreshDir', '目录-刷新', '1', 'esop_doc_view', 'esop:doc:refreshDir', '1', '文档管理--目录--刷新', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_doc_add', '上传', '1', 'esop_doc_view', 'esop:doc:add', '1', '文档管理--上传', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_doc_preview', '预览', '1', 'esop_doc_view', 'esop:doc:preview', '1', '文档管理--预览', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_doc_update', '修改', '1', 'esop_doc_view', 'esop:doc:update', '1', '文档管理--修改', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_doc_delete', '删除', '1', 'esop_doc_view', 'esop:doc:delete', '1', '文档管理--删除', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_doc_review', '审核', '1', 'esop_doc_view', 'esop:doc:review', '1', '文档管理--审核', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_doc_discardReview', '弃审', '1', 'esop_doc_view', 'esop:doc:discardReview', '1', '文档管理--弃审', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_doc_freeze', '冻结', '1', 'esop_doc_view', 'esop:doc:freeze', '1', '文档管理--冻结', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_doc_activate', '激活', '1', 'esop_doc_view', 'esop:doc:activate', '1', '文档管理--激活', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_doc_refresh', '刷新', '1', 'esop_doc_view', 'esop:doc:refresh', '1', '文档管理--刷新', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_doc_filter', '过滤', '1', 'esop_doc_view', 'esop:doc:filter', '1', '文档管理--过滤', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_workTemplate_add', '新增', '1', 'esop_workTemplate_view', 'esop:workTemplate:add', '1', '作业模板--新增', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_workTemplate_delete', '删除', '1', 'esop_workTemplate_view', 'esop:workTemplate:delete', '1', '作业模板--删除', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_workTemplate_update', '修改', '1', 'esop_workTemplate_view', 'esop:workTemplate:update', '1', '作业模板--修改', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_workTemplate_refresh', '刷新', '1', 'esop_workTemplate_view', 'esop:workTemplate:refresh', '1', '作业模板--刷新', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_workTemplate_filter', '过滤', '1', 'esop_workTemplate_view', 'esop:workTemplate:filter', '1', '作业模板--过滤', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_workTemplate_import', '导入', '1', 'esop_workTemplate_view', 'esop:workTemplate:import', '0', '作业模板--导入', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_workTemplate_export', '导出', '1', 'esop_workTemplate_view', 'esop:workTemplate:export', '0', '作业模板--导出', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_workTemplate_distribute', '发放', '1', 'esop_workTemplate_view', 'esop:workTemplate:distribute', '1', '作业模板--发放', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_workTemplate_preview', '预览', '1', 'esop_workTemplate_view', 'esop:workTemplate:preview', '1', '作业模板--预览', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_workInfo_add', '新增', '1', 'esop_workInfo_view', 'esop:workInfo:add', '1', '作业计划--新增', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_workInfo_delete', '删除', '1', 'esop_workInfo_view', 'esop:workInfo:delete', '1', '作业计划--删除', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_workInfo_update', '修改', '1', 'esop_workInfo_view', 'esop:workInfo:update', '1', '作业计划--修改', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_workInfo_refresh', '刷新', '1', 'esop_workInfo_view', 'esop:workInfo:refresh', '1', '作业计划--刷新', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_workInfo_filter', '过滤', '1', 'esop_workInfo_view', 'esop:workInfo:filter', '1', '作业计划--过滤', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_workInfo_import', '导入', '1', 'esop_workInfo_view', 'esop:workInfo:import', '0', '作业计划--导入', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_workInfo_export', '导出', '1', 'esop_workInfo_view', 'esop:workInfo:export', '0', '作业计划--导出', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_workInfo_preview', '预览', '1', 'esop_workInfo_view', 'esop:workInfo:preview', '1', '作业计划--预览', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_workInfo_distribute', '发放', '1', 'esop_workInfo_view', 'esop:workInfo:distribute', '1', '作业计划--发放', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_workInfo_finish', '结束', '1', 'esop_workInfo_view', 'esop:workInfo:finish', '1', '作业计划--结束', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_stationMonitior_workInfo', '作业计划', '1', 'esop_stationMonitior_view', 'esop:stationMonitior:workInfo', '1', '工位监控--作业计划', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_stationMonitior_add', '新增作业', '1', 'esop_stationMonitior_view', 'esop:stationMonitior:add', '1', '工位监控--新增作业', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_stationMonitior_refresh', '刷新', '1', 'esop_stationMonitior_view', 'esop:stationMonitior:refresh', '1', '工位监控--刷新', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_notice_add', '新增', '1', 'esop_notice_view', 'esop:notice:add', '1', '通知管理--新增', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_notice_delete', '删除', '1', 'esop_notice_view', 'esop:notice:delete', '1', '通知管理--删除', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_notice_update', '修改', '1', 'esop_notice_view', 'esop:notice:update', '1', '通知管理--修改', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_notice_refresh', '刷新', '1', 'esop_notice_view', 'esop:notice:refresh', '1', '通知管理--刷新', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_notice_filter', '过滤', '1', 'esop_notice_view', 'esop:notice:filter', '1', '通知管理--过滤', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_notice_import', '导入', '1', 'esop_notice_view', 'esop:notice:import', '0', '通知管理--导入', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_notice_export', '导出', '1', 'esop_notice_view', 'esop:notice:export', '0', '通知管理--导出', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_notice_broadcast', '广播', '1', 'esop_notice_view', 'esop:notice:broadcast', '1', '通知管理--广播', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_notice_style', '通知样式', '1', 'esop_notice_view', 'esop:notice:style', '1', '通知管理--通知样式', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_noticeDetail_stop', '停止', '1', 'esop_noticeDetail_view', 'esop:noticeDetail:stop', '1', '通知记录--停止', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_noticeDetail_delete', '删除', '1', 'esop_noticeDetail_view', 'esop:noticeDetail:delete', '1', '通知记录--删除', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_noticeDetail_refresh', '刷新', '1', 'esop_noticeDetail_view', 'esop:noticeDetail:refresh', '1', '通知记录--刷新', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_noticeDetail_filter', '过滤', '1', 'esop_noticeDetail_view', 'esop:noticeDetail:filter', '1', '通知记录--过滤', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_andonItem_add', '新增', '1', 'esop_andonItem_view', 'esop:andonItem:add', '1', '安灯项--新增', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_andonItem_delete', '删除', '1', 'esop_andonItem_view', 'esop:andonItem:delete', '1', '安灯项--删除', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_andonItem_update', '修改', '1', 'esop_andonItem_view', 'esop:andonItem:update', '1', '安灯项--修改', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_andonItem_refresh', '刷新', '1', 'esop_andonItem_view', 'esop:andonItem:refresh', '1', '安灯项--刷新', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_andonItem_filter', '过滤', '1', 'esop_andonItem_view', 'esop:andonItem:filter', '1', '安灯项--过滤', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_andonItem_import', '导入', '1', 'esop_andonItem_view', 'esop:andonItem:import', '0', '安灯项--导入', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_andonItem_export', '导出', '1', 'esop_andonItem_view', 'esop:andonItem:export', '0', '安灯项--导出', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_andonItem_color', '安灯颜色', '1', 'esop_andonItem_view', 'esop:andonItem:color', '1', '安灯项--安灯颜色', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_andonRecord_add', '新增', '1', 'esop_andonRecord_view', 'esop:andonRecord:add', '1', '安灯记录--新增', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_andonRecord_delete', '删除', '1', 'esop_andonRecord_view', 'esop:andonRecord:delete', '1', '安灯记录--删除', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_andonRecord_update', '修改', '1', 'esop_andonRecord_view', 'esop:andonRecord:update', '1', '安灯记录--修改', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_andonRecord_refresh', '刷新', '1', 'esop_andonRecord_view', 'esop:andonRecord:refresh', '1', '安灯记录--刷新', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_andonRecord_filter', '过滤', '1', 'esop_andonRecord_view', 'esop:andonRecord:filter', '1', '安灯记录--过滤', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_andonRecord_import', '导入', '1', 'esop_andonRecord_view', 'esop:andonRecord:import', '0', '安灯记录--导入', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_andonRecord_export', '导出', '1', 'esop_andonRecord_view', 'esop:andonRecord:export', '1', '安灯记录--导出', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_procReqmst_add', '新增', '1', 'esop_procReqmst_view', 'esop:procReqmst:add', '1', '生产订单--新增', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_procReqmst_delete', '删除', '1', 'esop_procReqmst_view', 'esop:procReqmst:delete', '1', '生产订单--删除', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_procReqmst_update', '修改', '1', 'esop_procReqmst_view', 'esop:procReqmst:update', '1', '生产订单--修改', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_procReqmst_refresh', '刷新', '1', 'esop_procReqmst_view', 'esop:procReqmst:refresh', '1', '生产订单--刷新', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_procReqmst_filter', '过滤', '1', 'esop_procReqmst_view', 'esop:procReqmst:filter', '1', '生产订单--过滤', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_procReqmst_review', '审核', '1', 'esop_procReqmst_view', 'esop:procReqmst:review', '1', '生产订单--审核', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_procReqmst_discardReview', '弃审', '1', 'esop_procReqmst_view', 'esop:procReqmst:discardReview', '1', '生产订单--弃审', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_procReqmst_print', '打印', '1', 'esop_procReqmst_view', 'esop:procReqmst:print', '1', '生产订单--打印', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_simplePlan_add', '新增', '1', 'esop_simplePlan_view', 'esop:simplePlan:add', '1', '产线计划--新增', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_simplePlan_delete', '删除', '1', 'esop_simplePlan_view', 'esop:simplePlan:delete', '1', '产线计划--删除', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_simplePlan_update', '修改', '1', 'esop_simplePlan_view', 'esop:simplePlan:update', '1', '产线计划--修改', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_simplePlan_refresh', '刷新', '1', 'esop_simplePlan_view', 'esop:simplePlan:refresh', '1', '产线计划--刷新', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_simplePlan_filter', '过滤', '1', 'esop_simplePlan_view', 'esop:simplePlan:filter', '1', '产线计划--过滤', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_simplePlan_import', '导入', '1', 'esop_simplePlan_view', 'esop:simplePlan:import', '1', '产线计划--导入', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_simplePlan_export', '导出', '1', 'esop_simplePlan_view', 'esop:simplePlan:export', '1', '产线计划--导出', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_simplePlan_print', '打印', '1', 'esop_simplePlan_view', 'esop:simplePlan:print', '1', '产线计划--打印', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_simplePlan_plan', '计划', '1', 'esop_simplePlan_view', 'esop:simplePlan:plan', '1', '产线计划--计划', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_simplePlan_start', '开工', '1', 'esop_simplePlan_view', 'esop:simplePlan:start', '1', '产线计划--开工', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_simplePlan_finish', '完工', '1', 'esop_simplePlan_view', 'esop:simplePlan:finish', '1', '产线计划--完工', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productPlan_add', '新增', '1', 'esop_productPlan_view', 'esop:productPlan:add', '1', '产线计划--新增', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productPlan_delete', '删除', '1', 'esop_productPlan_view', 'esop:productPlan:delete', '1', '产线计划--删除', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productPlan_update', '修改', '1', 'esop_productPlan_view', 'esop:productPlan:update', '1', '产线计划--修改', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productPlan_refresh', '刷新', '1', 'esop_productPlan_view', 'esop:productPlan:refresh', '1', '产线计划--刷新', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productPlan_filter', '过滤', '1', 'esop_productPlan_view', 'esop:productPlan:filter', '1', '产线计划--过滤', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productPlan_import', '导入', '1', 'esop_productPlan_view', 'esop:productPlan:import', '1', '产线计划--导入', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productPlan_export', '导出', '1', 'esop_productPlan_view', 'esop:productPlan:export', '1', '产线计划--导出', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productPlan_print', '打印', '1', 'esop_productPlan_view', 'esop:productPlan:print', '1', '产线计划--打印', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productPlan_plan', '计划', '1', 'esop_productPlan_view', 'esop:productPlan:plan', '1', '产线计划--计划', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productPlan_start', '开工', '1', 'esop_productPlan_view', 'esop:productPlan:start', '1', '产线计划--开工', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productPlan_finish', '完工', '1', 'esop_productPlan_view', 'esop:productPlan:finish', '1', '产线计划--完工', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productPlan_report', '报工', '1', 'esop_productPlan_view', 'esop:productPlan:report', '1', '产线计划--报工', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productPlan_rework', '返工', '1', 'esop_productPlan_view', 'esop:productPlan:rework', '1', '产线计划--返工', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productPlan_picking', '领料', '1', 'esop_productPlan_view', 'esop:productPlan:picking', '1', '产线计划--领料', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productPlan_discardPicking', '弃领', '1', 'esop_productPlan_view', 'esop:productPlan:discardPicking', '1', '产线计划--弃领', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productPlan_reports', '报工记录', '1', 'esop_productPlan_view', 'esop:productPlan:reports', '1', '产线计划--报工记录', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productReport_add', '新增', '1', 'esop_productReport_view', 'esop:productReport:add', '1', '报工记录--新增', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productReport_delete', '删除', '1', 'esop_productReport_view', 'esop:productReport:delete', '1', '报工记录--删除', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productReport_update', '修改', '1', 'esop_productReport_view', 'esop:productReport:update', '1', '报工记录--修改', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productReport_refresh', '刷新', '1', 'esop_productReport_view', 'esop:productReport:refresh', '1', '报工记录--刷新', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productReport_filter', '过滤', '1', 'esop_productReport_view', 'esop:productReport:filter', '1', '报工记录--过滤', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productReport_import', '导入', '1', 'esop_productReport_view', 'esop:productReport:import', '0', '报工记录--导入', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_productReport_export', '导出', '1', 'esop_productReport_view', 'esop:productReport:export', '1', '报工记录--导出', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_customLib_add', '新增', '1', 'esop_customLib_view', 'esop:customLib:add', '0', '不良图库--新增', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_customLib_delete', '删除', '1', 'esop_customLib_view', 'esop:customLib:delete', '0', '不良图库--删除', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_customLib_update', '修改', '1', 'esop_customLib_view', 'esop:customLib:update', '0', '不良图库--修改', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_customLib_refresh', '刷新', '1', 'esop_customLib_view', 'esop:customLib:refresh', '0', '不良图库--刷新', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_customLib_filter', '过滤', '1', 'esop_customLib_view', 'esop:customLib:filter', '0', '不良图库--过滤', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_customLib_import', '导入', '1', 'esop_customLib_view', 'esop:customLib:import', '0', '不良图库--导入', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_customLib_export', '导出', '1', 'esop_customLib_view', 'esop:customLib:export', '0', '不良图库--导出', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_customLib_addBatch', '批量添加', '1', 'esop_customLib_view', 'esop:customLib:addBatch', '0', '不良图库--批量添加', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_customLib_preview', '预览', '1', 'esop_customLib_view', 'esop:customLib:preview', '0', '不良图库--预览', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_kanBan_add', '新增', '1', 'esop_kanBan_view', 'esop:kanBan:add', '1', '看板管理--新增', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_kanBan_delete', '删除', '1', 'esop_kanBan_view', 'esop:kanBan:delete', '1', '看板管理--删除', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_kanBan_update', '修改', '1', 'esop_kanBan_view', 'esop:kanBan:update', '1', '看板管理--修改', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_kanBan_preview', '预览', '1', 'esop_kanBan_view', 'esop:kanBan:preview', '0', '看板管理--预览', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_kanBan_refresh', '刷新', '1', 'esop_kanBan_view', 'esop:kanBan:refresh', '1', '看板管理--刷新', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'system_role_add', '新增', '1', 'system_role_view', 'system:role:add', '1', '角色管理--新增', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'system_role_delete', '删除', '1', 'system_role_view', 'system:role:delete', '1', '角色管理--删除', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'system_role_update', '修改', '1', 'system_role_view', 'system:role:update', '1', '角色管理--修改', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'system_role_refresh', '刷新', '1', 'system_role_view', 'system:role:refresh', '1', '角色管理--刷新', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'system_role_filter', '过滤', '1', 'system_role_view', 'system:role:filter', '1', '角色管理--过滤', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'system_role_import', '导入', '1', 'system_role_view', 'system:role:import', '0', '角色管理--导入', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'system_role_export', '导出', '1', 'system_role_view', 'system:role:export', '0', '角色管理--导出', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'system_role_auth', '权限', '1', 'system_role_view', 'system:role:auth', '1', '角色管理--权限', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'system_role_users', '包含用户', '1', 'system_role_view', 'system:role:users', '1', '角色管理--包含用户', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'system_user_add', '新增', '1', 'system_user_view', 'system:user:add', '1', '用户管理--新增', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'system_user_delete', '删除', '1', 'system_user_view', 'system:user:delete', '1', '用户管理--删除', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'system_user_update', '修改', '1', 'system_user_view', 'system:user:update', '1', '用户管理--修改', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'system_user_refresh', '刷新', '1', 'system_user_view', 'system:user:refresh', '1', '用户管理--刷新', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'system_user_filter', '过滤', '1', 'system_user_view', 'system:user:filter', '1', '用户管理--过滤', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'system_user_import', '导入', '1', 'system_user_view', 'system:user:import', '1', '用户管理--导入', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'system_user_export', '导出', '1', 'system_user_view', 'system:user:export', '0', '用户管理--导出', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'system_user_roles', '所属角色', '1', 'system_user_view', 'system:user:roles', '1', '用户管理--所属角色', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_terminal_report', '报工', '1', 'esop_terminal_view', 'esop:terminal:report', '1', '终端权限--报工', '');
insert into sys_Resource(resourceCode, resourceName, permissionType, parentCode, permission, available, descript, includedCmd) values( 'esop_terminal_rework', '返工', '1', 'esop_terminal_view', 'esop:terminal:rework', '1', '终端权限--返工', '');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_prodLine_add');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_prodLine_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_prodLine_update');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_prodLine_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_prodLine_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_prodLine_import');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_prodLine_export');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_prodLine_employee');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_procedureDictionary_add');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_procedureDictionary_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_procedureDictionary_update');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_procedureDictionary_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_procedureDictionary_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_procedureDictionary_import');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_procedureDictionary_export');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_station_add');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_station_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_station_update');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_station_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_station_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_station_import');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_station_export');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_product_add');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_product_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_product_update');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_product_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_product_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_product_import');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_product_export');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_product_preview');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_dept_add');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_dept_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_dept_update');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_dept_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_dept_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_dept_import');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_processRoute_add');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_processRoute_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_processRoute_update');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_processRoute_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_processRoute_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_doc_addDir');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_doc_updateDir');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_doc_deleteDir');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_doc_refreshDir');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_doc_add');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_doc_preview');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_doc_update');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_doc_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_doc_review');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_doc_discardReview');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_doc_freeze');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_doc_activate');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_doc_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_doc_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_workTemplate_add');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_workTemplate_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_workTemplate_update');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_workTemplate_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_workTemplate_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_workTemplate_import');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_workTemplate_export');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_workTemplate_distribute');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_workTemplate_preview');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_workInfo_add');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_workInfo_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_workInfo_update');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_workInfo_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_workInfo_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_workInfo_import');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_workInfo_export');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_workInfo_preview');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_workInfo_distribute');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_workInfo_finish');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_stationMonitior_workInfo');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_stationMonitior_add');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_stationMonitior_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_notice_add');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_notice_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_notice_update');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_notice_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_notice_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_notice_import');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_notice_export');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_notice_broadcast');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_notice_style');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_noticeDetail_stop');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_noticeDetail_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_noticeDetail_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_noticeDetail_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_andonItem_add');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_andonItem_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_andonItem_update');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_andonItem_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_andonItem_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_andonItem_import');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_andonItem_export');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_andonItem_color');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_andonRecord_add');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_andonRecord_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_andonRecord_update');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_andonRecord_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_andonRecord_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_andonRecord_import');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_andonRecord_export');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_procReqmst_add');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_procReqmst_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_procReqmst_update');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_procReqmst_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_procReqmst_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_procReqmst_review');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_procReqmst_discardReview');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_procReqmst_print');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_simplePlan_add');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_simplePlan_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_simplePlan_update');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_simplePlan_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_simplePlan_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_simplePlan_import');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_simplePlan_export');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_simplePlan_print');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_simplePlan_plan');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_simplePlan_start');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_simplePlan_finish');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productPlan_add');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productPlan_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productPlan_update');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productPlan_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productPlan_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productPlan_import');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productPlan_export');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productPlan_print');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productPlan_plan');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productPlan_start');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productPlan_finish');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productPlan_report');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productPlan_rework');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productPlan_picking');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productPlan_discardPicking');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productPlan_reports');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productReport_add');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productReport_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productReport_update');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productReport_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productReport_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productReport_import');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_productReport_export');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_customLib_add');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_customLib_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_customLib_update');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_customLib_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_customLib_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_customLib_import');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_customLib_export');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_customLib_addBatch');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_customLib_preview');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_kanBan_add');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_kanBan_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_kanBan_update');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_kanBan_preview');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_kanBan_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'system_role_add');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'system_role_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'system_role_update');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'system_role_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'system_role_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'system_role_import');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'system_role_export');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'system_role_auth');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'system_role_users');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'system_user_add');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'system_user_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'system_user_update');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'system_user_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'system_user_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'system_user_import');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'system_user_export');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'system_user_roles');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_terminal_report');
insert into sys_RoleResource(roleCode, resourceCode) values('default', 'esop_terminal_rework');
insert into sys_RoleResource(roleCode, resourceCode) values('admin', 'system_role_add');
insert into sys_RoleResource(roleCode, resourceCode) values('admin', 'system_role_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('admin', 'system_role_update');
insert into sys_RoleResource(roleCode, resourceCode) values('admin', 'system_role_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('admin', 'system_role_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('admin', 'system_role_import');
insert into sys_RoleResource(roleCode, resourceCode) values('admin', 'system_role_export');
insert into sys_RoleResource(roleCode, resourceCode) values('admin', 'system_role_auth');
insert into sys_RoleResource(roleCode, resourceCode) values('admin', 'system_role_users');
insert into sys_RoleResource(roleCode, resourceCode) values('admin', 'system_user_add');
insert into sys_RoleResource(roleCode, resourceCode) values('admin', 'system_user_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('admin', 'system_user_update');
insert into sys_RoleResource(roleCode, resourceCode) values('admin', 'system_user_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('admin', 'system_user_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('admin', 'system_user_import');
insert into sys_RoleResource(roleCode, resourceCode) values('admin', 'system_user_export');
insert into sys_RoleResource(roleCode, resourceCode) values('admin', 'system_user_roles');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_prodLine_add');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_prodLine_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_prodLine_update');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_prodLine_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_prodLine_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_prodLine_import');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_prodLine_export');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_prodLine_employee');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_procedureDictionary_add');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_procedureDictionary_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_procedureDictionary_update');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_procedureDictionary_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_procedureDictionary_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_procedureDictionary_import');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_procedureDictionary_export');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_station_add');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_station_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_station_update');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_station_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_station_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_station_import');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_station_export');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_product_add');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_product_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_product_update');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_product_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_product_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_product_import');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_product_export');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_product_preview');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_dept_add');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_dept_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_dept_update');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_dept_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_dept_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_dept_import');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_processRoute_add');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_processRoute_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_processRoute_update');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_processRoute_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_processRoute_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_doc_addDir');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_doc_updateDir');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_doc_deleteDir');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_doc_refreshDir');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_doc_add');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_doc_preview');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_doc_update');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_doc_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_doc_review');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_doc_discardReview');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_doc_freeze');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_doc_activate');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_doc_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_doc_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_workTemplate_add');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_workTemplate_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_workTemplate_update');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_workTemplate_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_workTemplate_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_workTemplate_import');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_workTemplate_export');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_workTemplate_distribute');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_workTemplate_preview');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_workInfo_add');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_workInfo_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_workInfo_update');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_workInfo_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_workInfo_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_workInfo_import');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_workInfo_export');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_workInfo_preview');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_workInfo_distribute');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_workInfo_finish');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_stationMonitior_workInfo');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_stationMonitior_add');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_stationMonitior_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_notice_add');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_notice_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_notice_update');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_notice_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_notice_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_notice_import');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_notice_export');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_notice_broadcast');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_notice_style');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_noticeDetail_stop');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_noticeDetail_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_noticeDetail_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_noticeDetail_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_andonItem_add');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_andonItem_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_andonItem_update');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_andonItem_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_andonItem_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_andonItem_import');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_andonItem_export');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_andonItem_color');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_andonRecord_add');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_andonRecord_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_andonRecord_update');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_andonRecord_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_andonRecord_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_andonRecord_import');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_andonRecord_export');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_procReqmst_add');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_procReqmst_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_procReqmst_update');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_procReqmst_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_procReqmst_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_procReqmst_review');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_procReqmst_discardReview');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_procReqmst_print');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_simplePlan_add');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_simplePlan_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_simplePlan_update');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_simplePlan_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_simplePlan_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_simplePlan_import');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_simplePlan_export');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_simplePlan_print');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_simplePlan_plan');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_simplePlan_start');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_simplePlan_finish');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productPlan_add');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productPlan_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productPlan_update');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productPlan_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productPlan_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productPlan_import');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productPlan_export');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productPlan_print');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productPlan_plan');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productPlan_start');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productPlan_finish');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productPlan_report');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productPlan_rework');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productPlan_picking');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productPlan_discardPicking');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productPlan_reports');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productReport_add');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productReport_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productReport_update');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productReport_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productReport_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productReport_import');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_productReport_export');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_customLib_add');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_customLib_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_customLib_update');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_customLib_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_customLib_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_customLib_import');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_customLib_export');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_customLib_addBatch');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_customLib_preview');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_kanBan_add');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_kanBan_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_kanBan_update');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_kanBan_preview');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_kanBan_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'system_role_add');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'system_role_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'system_role_update');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'system_role_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'system_role_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'system_role_import');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'system_role_export');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'system_role_auth');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'system_role_users');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'system_user_add');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'system_user_delete');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'system_user_update');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'system_user_refresh');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'system_user_filter');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'system_user_import');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'system_user_export');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'system_user_roles');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_terminal_report');
insert into sys_RoleResource(roleCode, resourceCode) values('all', 'esop_terminal_rework');
