server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        # Nacos 服务注册中心地址
        server-addr: localhost:8848
    sentinel:
      transport:
        # 配置 Sentinel dashboard 地址
        dashboard: localhost:8080
        # 默认 8719 端口，加入被占用会自动从 8719 开始依次 +1 扫描，直至找到未被占用的端口
        port: 8719
      datasource:
        #Sentinel数据源 - 流控规则配置
        flow:
          nacos:
            serverAddr: 192.168.11.99:8848
            dataId: ${spring.application.name}-flow-rules
            groupId: DEFAULT_GROUP
            dataType: json
            rule-type: flow
        #Sentinel数据源 - 降级规则配置
        degrade:
          nacos:
            serverAddr: 192.168.11.99:8848
            dataId: ${spring.application.name}-degrade-rules
            groupId: DEFAULT_GROUP
            dataType: json
            rule-type: degrade
#  resource：资源名称；
#  limitApp：来源应用；
#  grade：阈值类型，0表示线程数，1表示QPS；
#  count：单机阈值；
#  strategy：流控模式，0表示直接，1表示关联，2表示链路；
#  controlBehavior：流控效果，0表示快速失败，1表示Warm Up，2表示排队等待；
#  clusterMode：是否集群。
#[
#  {
#    "resource": "customerBlockHandler",
#    "limitApp": "default",
#    "grade": 1,
#    "count": 5,
#    "strategy": 0,
#    "controlBehavior": 0,
#    "clusterMode": false
#  }
#]
management:
  endpoints:
    web:
      exposure:
        include: '*'

#java -Dserver.port=5020 -Dcsp.sentinel.dashboard.server=localhost:5020 -Dproject.name=sentinel-dashboard -jar sentinel-dashboard-1.8.6.jar
