# 8011 表示注册到 zookeeper 服务器的支付服务提供者端口号
server:
  port: 8011

# 服务别名----注册 zookeeper 到注册中心名称
spring:
  application:
    name: cloud-consumer-order
  cloud:
    zookeeper:
      connect-string: 192.168.56.101:2181